# build.yaml

targets:
  $default:
    builders:
      # Drift 코드 생성기 설정
      drift_dev:
        # generate_for는 이 빌더가 어떤 파일들을 분석할지 범위를 지정하는 옵션입니다.
        # 이 부분이 가장 중요합니다.
        generate_for:
          # 데이터베이스 관련 파일(database.dart, dao 파일 등)이 있는 경로를 지정합니다.
          # 만약 경로가 다르다면 이 부분을 실제 프로젝트에 맞게 수정해주세요.
          - lib/data/local/**.dart

      # 모든 코드 생성기가 생성된 .g.dart 파일을 다시 분석하지 않도록 하는
      # 전역 설정입니다. 코드 생성기 간의 충돌을 방지합니다.
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - type=lint