// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKZYaPK98gHuArygPUsDXwmzEyAF0Mqe4',
    appId: '1:546590111912:web:ffc4b0b466d1e21853ea9d',
    messagingSenderId: '546590111912',
    projectId: 'costgobookkeeping',
    authDomain: 'costgobookkeeping.firebaseapp.com',
    storageBucket: 'costgobookkeeping.firebasestorage.app',
    measurementId: 'G-938EVGNWVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4uSUkX2RsGRUmBwmlIpo7BF9HgiW5wtU',
    appId: '1:546590111912:android:c894211546b5d6e453ea9d',
    messagingSenderId: '546590111912',
    projectId: 'costgobookkeeping',
    storageBucket: 'costgobookkeeping.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT5I4bVc61G9OdlsfVA6GqVaSD9xJcKGc',
    appId: '1:546590111912:ios:d01867c75ee422b153ea9d',
    messagingSenderId: '546590111912',
    projectId: 'costgobookkeeping',
    storageBucket: 'costgobookkeeping.firebasestorage.app',
    iosBundleId: 'com.example.bookkeepingFreshStart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT5I4bVc61G9OdlsfVA6GqVaSD9xJcKGc',
    appId: '1:546590111912:ios:d01867c75ee422b153ea9d',
    messagingSenderId: '546590111912',
    projectId: 'costgobookkeeping',
    storageBucket: 'costgobookkeeping.firebasestorage.app',
    iosBundleId: 'com.example.bookkeepingFreshStart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKZYaPK98gHuArygPUsDXwmzEyAF0Mqe4',
    appId: '1:546590111912:web:a5583a699de7335753ea9d',
    messagingSenderId: '546590111912',
    projectId: 'costgobookkeeping',
    authDomain: 'costgobookkeeping.firebaseapp.com',
    storageBucket: 'costgobookkeeping.firebasestorage.app',
    measurementId: 'G-NT7WK2SM0C',
  );
}
